# SimpleExploitFixer

# Respawn Anchor
DisableRespawnAnchorExplosions: false

# Armor stands
FixArmorStandLag: true

# Chunk Ban
PreventChunkBan: true
MaxItemFramePerChunk: 5

MaxEnchantingTablePerChunk: 6
MaxEnderchestPerChunk: 15
MaxHopperPerChunk: 5
MaxSlimePerChunk: 20
MaxBeaconPerChunk: 8
MaxGlowstonePerChunk: 64
MaxContainerPerChunk: 25
MaxArmorStandPerChunk: 10
MaxRepeaterPerChunk: 10
StrictArmorStandCheck: true

RemoveChunkBansOnChunkLoad: false
RemoveEnchantingTablesOnChunkLoad: false
RemoveEnderChestsOnChunkLoad: false
RemoveHoppersOnChunkLoad: false
RemoveSlimeBlocksOnChunkLoad: false
RemoveBeaconsOnChunkLoad: false
RemoveGlowStoneOnChunkLoad: false
RemoveContainersOnChunkLoad: false
RemoveArmorStandOnChunkLoad: false
RemoveRepeatersOnChunkLoad: false

# Bees
LimitBeesOnChunkLoad/UnLoad: true
StrictBeeCheck: true
MaxBeesPerChunk: 10

# Mobs
Zombie: false
Skeleton: false
Spider: false
CaveSpider: false
Creeper: false
Enderman: false
Phantom: false
Wither: false

# Wither Lag
RemoveWitherHeadsAutomatically: true
DisableWitherSkulls: false

# Links
PreventAllLinks: false

# Entity Checks
PreventTooManyEntitiesInChunk: true
MaxEntitiesInChunk: 100
LogEntityRemovals: false
EntityCheckTimeTicks: 20 #THIS IS IN SECONDS!

# Redstone Lag
LimitRedstonePlaced: true
MaxRedstonePerChunk: 24
LimitRedstoneOnChunkLoad: false
DisableRedstoneAtMaxPerChunk: true

PreventRailUpdateLag: true
DelayOfRailClock: 1

# Bow Bomb exploit
PreventBowBombExploit: true
MaxBowSquaredVelocity: 15

# Log4Shell
Log4J: true

# ProtocolLib
DisableAllProtocolLib: false
PreventNoComCoordinateExploit: true
NoComMaxDistance: 64

StrictGroundItemCheck: true
MaxItemPerChunk: 25

# Tab Complete
SendFakePlugins: true

FakePluginList:
  - "PenisPlugin v4.20"
  - "You trying to exploit v6.9?"
  - "KYS v9.11"