# SimpleExploitFixer

# Bees
LimitBeesOnChunkLoad/UnLoad: true
StrictBeeCheck: true
MaxBeesPerChunk: 10

# Mobs
Zombie: false
Skeleton: false
Spider: false
CaveSpider: false
Creeper: false
Enderman: false
Phantom: false