# SimpleExploitFixer

# Chunk Ban
PreventChunkBan: true
MaxItemFramePerChunk: 5

MaxEnchantingTablePerChunk: 6
MaxEnderchestPerChunk: 15
MaxHopperPerChunk: 5
MaxSlimePerChunk: 20
MaxBeaconPerChunk: 8
MaxGlowstonePerChunk: 64
MaxContainerPerChunk: 25

RemoveChunkBansOnChunkLoad: false
RemoveEnchantingTablesOnChunkLoad: false
RemoveEnderChestsOnChunkLoad: false
RemoveHoppersOnChunkLoad: false
RemoveSlimeBlocksOnChunkLoad: false
RemoveBeaconsOnChunkLoad: false
RemoveGlowStoneOnChunkLoad: false
RemoveContainersOnChunkLoad: false

# Bees
LimitBeesOnChunkLoad/UnLoad: true
StrictBeeCheck: true
MaxBeesPerChunk: 10

# Mobs
Zombie: false
Skeleton: false
Spider: false
CaveSpider: false
Creeper: false
Enderman: false
Phantom: false
Wither: false

RemoveWitherHeadsAutomatically: true

# ProtocolLib
DisableAllProtocolLib: false
PreventNoComCoordinateExploit: true
NoComMaxDistance: 64